FROM alpine:latest
RUN apk add --no-cache openjdk8
RUN apk add --no-cache curl
WORKDIR /opt/appdynamics/machine-agent
COPY --from=dtr.corp.appdynamics.com/appdynamics/machine-agent /opt/appdynamics/machine-agent .
WORKDIR /opt/appdynamics/machine-agent/monitors
COPY target/ProcessMonitor-*.zip ProcessMonitor.zip
RUN unzip -q ProcessMonitor.zip && \
    rm ProcessMonitor.zip
WORKDIR /opt/appdynamics/machine-agent/monitors/ProcessMonitor
COPY src/integration-test/resources/conf/config.yml config.yml
# Setup JAVA_HOME
ENV JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk
ENV PATH="$JAVA_HOME/bin:${PATH}"
CMD ["sh", "-c", "java -jar process-monitoring-extension.jar"]

